sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
excludes:
  # Local changes in org.eclipse.jdt.core.prefs are required because this is built with Java 8
  - "E-PK-CORE-18: Outdated content: '.settings/org.eclipse.jdt.core.prefs'"
build:
  exasolDbVersions:
    - "8.27.0"
    - "7.1.26"
