sources:
  - type: maven
    path: pom.xml
    modules:
      - maven_central
      - integration_tests
excludes:
  - "E-PK-CORE-18: Outdated content: '.settings/org.eclipse.jdt.core.prefs'"
linkReplacements:
